//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPU()
        {
            this.Basket = new HashSet<Basket>();
            this.TovarToOrder = new HashSet<TovarToOrder>();
        }
    
        public int Id_Processor { get; set; }
        public string Model { get; set; }
        public string Soket { get; set; }
        public string Count_of_Cores { get; set; }
        public string Num_of_Threads { get; set; }
        public string Name_Core { get; set; }
        public string Base_CPU { get; set; }
        public string Max_CPU { get; set; }
        public bool CPU_overclocking { get; set; }
        public string Max_Memory { get; set; }
        public string TDP { get; set; }
        public bool Graphics_core { get; set; }
        public string Pic { get; set; }
        public Nullable<int> Coast { get; set; }
        public Nullable<int> Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarToOrder> TovarToOrder { get; set; }
    }
}
