//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<HDD> HDD { get; set; }
        public virtual DbSet<Monitor> Monitor { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PickUp> PickUp { get; set; }
        public virtual DbSet<PowerUnit> PowerUnit { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<TovarToOrder> TovarToOrder { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VideoCard> VideoCard { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
