//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monitor()
        {
            this.Basket = new HashSet<Basket>();
            this.TovarToOrder = new HashSet<TovarToOrder>();
        }
    
        public int Id_Monitor { get; set; }
        public string Model { get; set; }
        public string Diagonal { get; set; }
        public string Type_Matrix { get; set; }
        public string Max_Resolution { get; set; }
        public string frequency { get; set; }
        public string VideoConn { get; set; }
        public string PowerNeed { get; set; }
        public string Pic { get; set; }
        public Nullable<int> Coast { get; set; }
        public Nullable<int> Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarToOrder> TovarToOrder { get; set; }
    }
}
