//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.TovarToOrder = new HashSet<TovarToOrder>();
        }
    
        public int Id_Order { get; set; }
        public int Price { get; set; }
        public System.DateTime TimeOrder { get; set; }
        public string Status { get; set; }
        public Nullable<int> Id_User { get; set; }
        public string CodeOrder { get; set; }
        public Nullable<int> Id_PickUp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarToOrder> TovarToOrder { get; set; }
        public virtual Users Users { get; set; }
        public virtual PickUp PickUp { get; set; }
    }
}
