//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarToOrder
    {
        public int Id_TovarToOrder { get; set; }
        public int Id_User { get; set; }
        public Nullable<int> Id_Case { get; set; }
        public Nullable<int> Id_Processor { get; set; }
        public Nullable<int> Id_HDD { get; set; }
        public Nullable<int> Id_Monitor { get; set; }
        public Nullable<int> Id_Motherboard { get; set; }
        public Nullable<int> Id_PowerUnit { get; set; }
        public Nullable<int> Id_RAM { get; set; }
        public Nullable<int> Id_VideoCard { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Cases Cases { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual HDD HDD { get; set; }
        public virtual Monitor Monitor { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual PowerUnit PowerUnit { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual Users Users { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
