//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoCard()
        {
            this.Basket = new HashSet<Basket>();
            this.TovarToOrder = new HashSet<TovarToOrder>();
        }
    
        public int Id_VideoCard { get; set; }
        public string Model { get; set; }
        public string Count_Memory { get; set; }
        public string Type_Memory { get; set; }
        public string Memory_frequency { get; set; }
        public string Video_frequency { get; set; }
        public string Turbo { get; set; }
        public string Count_CPU { get; set; }
        public string Connector { get; set; }
        public string Conn_interface { get; set; }
        public string Power_Unit { get; set; }
        public string Pic { get; set; }
        public Nullable<int> Coast { get; set; }
        public Nullable<int> Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarToOrder> TovarToOrder { get; set; }
    }
}
