//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int Id_Worker { get; set; }
        public string Second_name { get; set; }
        public string First_name { get; set; }
        public string Father_name { get; set; }
        public string Job { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
